# Generated by Django 4.2.13 on 2024-05-31 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "assign_date",
                    models.DateField(
                        default=datetime.datetime(2024, 5, 31, 19, 56, 12, 69106)
                    ),
                ),
                ("category", models.ManyToManyField(to="category.categorymodel")),
            ],
        ),
    ]
